# Dependencies
markdown:         kramdown
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]

highlighter: rouge



# Permalinks
permalink:        pretty

# Setup
title:            Neel Smith on github
tagline:          'Openly available work in digital classics'
description:      'Some highlights of my openly available work on github'
#baseurl: http://neelsmith.github.io
baseurl: ""


author:
  name:           'Neel Smith'


paginate:         5



links:
  - title: Tagged blog posts
    url: /alltags
  - title: Greek
    url: /greek
  - title: Manuscripts
    url: /mss
  - title: Citation
    url: /citation
  - title: Writing digitally
    url: /writing
  - title: NS @ HC
    url: http://shot.holycross.edu/~nsmith/
    external: true
  - title: Github source repository
    url: https://github.com/neelsmith/neelsmith.github.io
    external: true
